### ISSUE TITLE
Ident binding of `fmt` from withing template

### ISSUE THREAD

**Issue by bluenote10** [vegansk/nimboost#14]
I discovered a small issue when using `fmt` from within a template:

```nimrod
import boost.richstring

template test(): untyped =
  let x = 1
  echo $x
  # fmt produces the same AST, but with ident instead of sym
  echo fmt "$x"

test()
```

This produces: `Error: undeclared identifier: 'x'`

The problem is a bit tricky, because the generated AST itself is fine, but apparently the `ident "x"` is not looked up in the template. I vaguely remember that I had the same problem in my old [nim stringinterpolation](https://github.com/bluenote10/nim-stringinterpolation) library, and never found a good solution to that.

By the way, I really like your stringinterpolation solution and I would love to see it in the standard library. What is the progress of https://github.com/nim-lang/Nim/issues/5600, is there anything left to do where I could help?

**Comment by vegansk** [comment]
@bluenote10, sorry, I was on vacation and saw it just now. I'll investigate it asap

**Comment by vegansk** [comment]
Use `inject` pragma:
```nim
import boost.richstring

template test(): untyped =
  let x{.inject.} = 1
  echo $x
  # fmt produces the same AST, but with ident instead of sym
  echo fmt "$x"

test()
```

Output:
```
1
1
```

**Comment by bluenote10** [comment]
Yes this is probably the best work-around. At first, I was a bit worried about giving up template hygiene, but in most cases it should be possible to avoid leaking symbols by using an explicit `block:` within the template. A solution without `{.inject.}` or `{.dirty.}` would probably require to modify how `parseExpr` works, i.e., it would have to lookup template symbols properly.

**Comment by bluenote10** [comment]
FYI I have opened on issue for this in Nim itself https://github.com/nim-lang/Nim/issues/6508 -- this issue could be resolved by making `parseExpr` aware of template symbols.
